apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    app: postgres
spec:
  containers:
  - name: postgres
    image: docker.io/yahiaelalfy/db-non-root:1.0
    imagePullPolicy: Always
    ports:
    - containerPort: 5432
      protocol: TCP
    env:
    - name: POSTGRES_DB
      value: webclinic
    - name: POSTGRES_USER
      value: postgres
    - name: POSTGRES_PASSWORD
      value: asdyfe2rd
    - name: PGDATA
      value: /temp/data
    resources:
      limits:
        cpu: 60m
        memory: 512Mi
      requests:
        cpu: 30m
        memory: 128Mi
    restartPolicy: Always
